const pool = require("./pool");

async function getAllStock() {
  try {
    const { rows } = await pool.query("SELECT * FROM stock");
    return rows;
  } catch (error) {
    console.error("Error retrieving all games from db: ", error);
  }
}

async function getGameDetails(stockID) {
  try {
    // Note to self: The key is "rows" (plural), NOT singular "row"
    const { rows } = await pool.query(
      "SELECT * FROM stock INNER JOIN game_details ON stock.stockid = game_details.stockid WHERE stock.stockid = $1",
      [stockID],
    );
    return rows;
  } catch (error) {
    console.error("Error getting game details from db: ", error);
  }
}

async function getFilteredGames(query) {
  console.log("query on db: ", query);
  console.log("key: ", Object.keys(query)[0]);
  console.log("value: ", query[Object.keys(query)[0]]);
  try {
    const { rows } = await pool.query(
      `SELECT * FROM stock INNER JOIN game_details ON stock.stockid = game_details.stockid WHERE $1 = $2`,
      [Object.keys(query)[0], query[Object.keys(query)[0]]],
    );

    console.log("rows to be returned by db: ", rows);
    return rows;
  } catch (error) {
    console.error("Error retrieving filtered games from db", error);
  }
}

async function getFilterCategories() {
  try {
    const systemQuery = await pool.query("SELECT DISTINCT system FROM stock");
    const developerQuery = await pool.query(
      "SELECT DISTINCT developer FROM game_details",
    );
    const publisherQuery = await pool.query(
      "SELECT DISTINCT publisher FROM game_details",
    );
    const genre = await pool.query("SELECT DISTINCT genre FROM game_details");
    const releaseYear = await pool.query(
      "SELECT DISTINCT releaseyear FROM game_details",
    );

    return {
      system: systemQuery.rows,
      developer: developerQuery.rows,
      publisher: publisherQuery.rows,
      genre: genre.rows,
      releaseyear: releaseYear.rows,
    };
  } catch (error) {
    console.error("Error retrieving filter categories: ", error);
  }
}

async function getSystemResults(system) {
  try {
    const { rows } = await pool.query(
      "SELECT *  FROM stock WHERE system = $1",
      [system],
    );
    return rows;
  } catch (error) {
    console.error("Error getting system category: ", error);
  }
}

async function getDeveloperResults(developer) {
  try {
    const { rows } = await pool.query(
      "SELECT stock.stockid, name, system, quantity, price  FROM stock INNER JOIN game_details ON stock.stockid = game_details.stockid WHERE developer = $1",
      [developer.replace(/_/g, " ")],
    );
    return rows;
  } catch (error) {
    console.error("Error getting system category: ", error);
  }
}

async function getPublisherResults(publisher) {
  try {
    const { rows } = await pool.query(
      "SELECT stock.stockid, name, system, quantity, price  FROM stock INNER JOIN game_details ON stock.stockid = game_details.stockid WHERE publisher = $1",
      [publisher.replace(/_/g, " ")],
    );
    return rows;
  } catch (error) {
    console.error("Error getting system category: ", error);
  }
}

async function getGenreResults(genre) {
  try {
    const { rows } = await pool.query(
      "SELECT stock.stockid, name, system, quantity, price FROM stock INNER JOIN game_details ON stock.stockid = game_details.stockid WHERE genre = $1",
      [genre.replace(/_/g, " ")],
    );
    return rows;
  } catch (error) {
    console.error("Error getting system category: ", error);
  }
}

async function getReleaseYearResults(releaseyear) {
  try {
    const { rows } = await pool.query(
      "SELECT stock.stockid, name, system, quantity, price FROM stock INNER JOIN game_details ON stock.stockid = game_details.stockid WHERE releaseyear = $1",
      [releaseyear],
    );
    return rows;
  } catch (error) {
    console.error("Error getting system category: ", error);
  }
}

async function postGameDetails(
  name,
  system,
  quantity,
  price,
  developer,
  publisher,
  genre,
  releaseyear,
) {
  // Dedicated client for error handling (rollback)
  const client = await pool.connect();

  try {
    await client.query("BEGIN");

    // Returning stockid in query since stockid (primary key) is auto generated by database
    const result = await client.query(
      `INSERT INTO stock (name, system, quantity, price) VALUES ($1, $2, $3, $4) RETURNING stockid;`,
      [name, system, quantity, price],
    );

    // Assign stockid to variable to be used as a foreign key in the next query
    const id = result.rows[0].stockid;

    const insertedDetails = await client.query(
      "INSERT INTO game_details (Developer, Publisher, Genre, ReleaseYear, stockID) VALUES ($1, $2, $3, $4, $5);",
      [developer, publisher, genre, releaseyear, id],
    );

    await client.query("COMMIT");

    // Object for frontend UI if needed
    return { id, details: insertedDetails.rows[0] };
  } catch (error) {
    await client.query("ROLLBACK");
    console.error("Error posting game details. Post method aborted: ", error);
  } finally {
    // Note to self: client is always released regardless of what happens
    client.release();
  }
}

async function postEditGameDetails(
  stockid,
  gameid,
  name,
  system,
  quantity,
  price,
  developer,
  publisher,
  genre,
  releaseyear,
) {
  const client = await pool.connect();

  try {
    await client.query("BEGIN");

    await client.query(
      `UPDATE stock SET name = $1, system = $2, quantity = $3, price = $4 WHERE stockid = $5`,
      [name, system, quantity, price, stockid],
    );

    await client.query(
      `UPDATE game_details SET developer = $1, publisher = $2, genre = $3, releaseyear = $4 WHERE gameid = $5`,
      [developer, publisher, genre, releaseyear, gameid],
    );

    await client.query(`COMMIT`);
  } catch (error) {
    await client.query(`ROLLBACK`);
    console.error("Error posting edit to database: ", error);
  } finally {
    client.release();
  }
}

async function removeGame(stockid) {
  const client = await pool.connect();

  try {
    await client.query(`DELETE FROM stock WHERE stockid = $1`, [stockid]);

    await client.query(`DELETE FROM game_details WHERE stockid = $1`, [
      stockid,
    ]);

    await client.query(`COMMIT`);
  } catch (error) {
    await client.query(`ROLLBACK`);
    console.error("error removing game from database", error);
  } finally {
    client.release();
  }
}

module.exports = {
  getAllStock,
  getGameDetails,
  getFilterCategories,
  getSystemResults,
  getDeveloperResults,
  getPublisherResults,
  getGenreResults,
  getReleaseYearResults,
  postGameDetails,
  postEditGameDetails,
  removeGame,
};
