const pool = require("./pool");

async function getAllStock() {
  try {
    const { rows } = await pool.query("SELECT * FROM stock");
    return rows;
  } catch (error) {
    console.error("Error retrieving all games from db: ", error);
  }
}

async function getGameDetails(stockID) {
  try {
    // Note to self: The key is "rows" (plural), NOT singular "row"
    const { rows } = await pool.query(
      "SELECT * FROM stock INNER JOIN game_details ON stock.stockid = game_details.stockid WHERE stock.stockid = $1",
      [stockID],
    );
    return rows;
  } catch (error) {
    console.error("Error getting game details from db: ", error);
  }
}

async function getFilteredGames(query) {
  console.log("query on db: ", query);
  console.log("key: ", Object.keys(query)[0]);
  console.log("value: ", query[Object.keys(query)[0]]);
  try {
    const { rows } = await pool.query(
      `SELECT * FROM stock INNER JOIN game_details ON stock.stockid = game_details.stockid WHERE $1 = $2`,
      [Object.keys(query)[0], query[Object.keys(query)[0]]],
    );

    console.log("rows to be returned by db: ", rows);
    return rows;
  } catch (error) {
    console.error("Error retrieving filtered games from db", error);
  }
}

async function postGameDetails(
  name,
  system,
  quantity,
  price,
  developer,
  publisher,
  genre,
  releaseyear,
) {
  // Dedicated client for error handling (rollback)
  const client = await pool.connect();

  try {
    await client.query("BEGIN");

    // Returning stockid in query since stockid (primary key) is auto generated by database
    const result = await client.query(
      `INSERT INTO stock (name, system, quantity, price) VALUES ($1, $2, $3, $4) RETURNING stockid;`,
      [name, system, quantity, price],
    );

    // Assign stockid to variable to be used as a foreign key in the next query
    const id = result.rows[0].stockid;

    const insertedDetails = await client.query(
      "INSERT INTO game_details (Developer, Publisher, Genre, ReleaseYear, stockID) VALUES ($1, $2, $3, $4, $5);",
      [developer, publisher, genre, releaseyear, id],
    );

    await client.query("COMMIT");

    // Object for frontend UI if needed
    return { id, details: insertedDetails.rows[0] };
  } catch (error) {
    await client.query("ROLLBACK");
    console.error("Error posting game details. Post method aborted: ", error);
  } finally {
    // Note to self: client is always released regardless of what happens
    client.release();
  }
}

module.exports = {
  getAllStock,
  getGameDetails,
  getFilteredGames,
  postGameDetails,
};
