const pool = require("./pool");

async function getAllStock() {
  try {
    const { rows } = await pool.query("SELECT * FROM stock");
    return rows;
  } catch (error) {
    console.error("db retrieval error: ", error);
  }
}

async function getGameDetails(stockID) {
  try {
    // Note to self: The key is "rows" (plural), NOT singular "row"
    const { rows } = await pool.query(
      "SELECT * FROM stock INNER JOIN game_details ON stock.stockid = game_details.stockid WHERE stock.stockid = $1",
      [stockID],
    );
    return rows;
  } catch (error) {
    console.error("Error getting game details: ", error);
  }
}

async function postGameDetails(
  name,
  system,
  quantity,
  price,
  developer,
  publisher,
  genre,
  releaseyear,
) {
  try {
    // Returning stockid in query since stockid (primary key) is auto generated by database
    const result = await pool.query(
      `INSERT INTO stock (name, console, quantity, price) VALUES ($1, $2, $3, $4) RETURNING stockid;`,
      [name, system, quantity, price],
    );

    // Assign stockid to variable to be used as a foreign key in the next query
    const id = result.rows[0].stockid;

    await pool.query(
      "INSERT INTO game_details (Developer, Publisher, Genre, ReleaseYear, stockID) VALUES ($1, $2, $3, $4, $5);",
      [developer, publisher, genre, releaseyear, id],
    );
  } catch (error) {
    console.error("Error posting game details", error);
  }
}

module.exports = {
  getAllStock,
  getGameDetails,
  postGameDetails,
};
